id: bigquery-controller
apiVersion: v1beta1
kind: ReplicationController
desiredState:
  replicas: 2
  # replicaSelector identifies the set of Pods that this
  # replicaController is responsible for managing
  replicaSelector:
    name: bigquery-controller
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: bqController
        containers:
          - name: bigquery
            # Change this to your docker hub username
            image: doctorproteus/pipeline
            env:
              - name: PROCESSINGSCRIPT
                value: redis-to-bigquery
              - name: REDISLIST
                value: twitter-stream
              # Change this to your project ID.
              - name: PROJECT_ID
                value: doctor-know
              # Change the following two settings to your dataset and table.
              - name: BQ_DATASET
                value: rtda
              - name: BQ_TABLE
                value: tweets
    # Important: these labels need to match the selector above
    # The api server enforces this constraint.
    labels:
      name: bigquery-controller
