apiVersion: v1beta1
id: redis-master-pod
kind: Pod
desiredState:
  manifest:
    version: v1beta1
    id: redis-master-pod
    containers:
      - name: redis-master
        image: dockerfile/redis
        ports:
          - containerPort: 6379
        volumeMounts:
            # name must match the volume name below
          - name: redis-persistent-storage
            # mount path within the container
            mountPath: /data/redis
    volumes:
      - name: redis-persistent-storage
        source:
          emptyDir: {}
labels:
  name: redis-master
  role: master
