id: twitter-stream-controller
apiVersion: v1beta1
kind: ReplicationController
desiredState:
  replicas: 1
  # replicaSelector identifies the set of Pods that this
  # replicaController is responsible for managing
  replicaSelector:
    name: twitter-stream
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: twitterStream
        containers:
          - name: twitter-to-redis
            # Change this to your docker hub username
            image: doctorproteus/pipeline
            env:
              - name: PROCESSINGSCRIPT
                value: twitter-to-redis
              - name: REDISLIST
                value: twitter-stream
              # Change the following four settings to your twitter credentials
              # information.
              - name: CONSUMERKEY
                value: 9xNrmD6hE0xnRSYdZt5t0XT0B
              - name: CONSUMERSECRET
                value: kperqjklvPhBCVvHI96aZIfJu5w1DHI2BZoNMdBEvBPfmuZIYG
              - name: ACCESSTOKEN
                value: 46501499-cijYvv9ixtQKHLSiLt9QaRtcmWeEKvvGZK5s6ukw7
              - name: ACCESSTOKENSEC
                value: D127XCAN02BPb0ZtcreCG6dpBJyiiLCeD6ckS2MgdHqwG
              - name: TWSTREAMMODE
                value: sample
    # Important: these labels need to match the selector above
    # The api server enforces this constraint.
    labels:
      name: twitter-stream
